refactor(grafana): Adapt cloudalchemy role to TDP
TOSIT-IO/tdp-observability pull request #56
Opened 2023-10-25 14:54 UTC by giem-git

#### Which issue(s) this PR fixes

Fixes #55

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-10-27 14:55 UTC, kpgtek requested changes

2023-10-27 14:55 UTC, kpgtek commented on requirements.yml
If this file is removed, I think there wil need to modify the [setup.sh](https://github.com/TOSIT-IO/tdp-observability/blob/main/scripts/setup.sh) script (installation by ```ansible-galaxy```).

2023-10-30 16:45 UTC, giem-git commented on requirements.yml
setup has been modified

2023-10-30 16:46 UTC, giem-git commented on roles/grafana/server/tasks/plugins.yml
> +  become: true
this is the file from cloudalchemy role. We dont use plugins in tdp, so we won't fix this

2023-10-30 16:46 UTC, giem-git commented on roles/grafana/server/templates/tmpfiles.j2
> +d {{ grafana_server.socket | dirname }} 0775 grafana grafana
fixed

2023-10-31 13:23 UTC, rpignolet approved these changes

2023-11-06 08:15 UTC, kpgtek approved these changes

2023-11-06 09:31 UTC, merged